version: "3.9"

x-kafka-env: &kafka-env
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  KAFKA_JMX_PORT: 9991
  KAFKA_DELETE_TOPIC_ENABLE: "true"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  KAFKA_DEFAULT_REPLICATION_FACTOR: 2
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
  KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
  KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
  KAFKA_SUPER_USERS: User:alex;User:kafka

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:${CONFLUENT_VERSION}
    restart: always
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka0:
    image: confluentinc/cp-kafka:${CONFLUENT_VERSION}
    hostname: kafka0
    container_name: kafka0
    ports:
      - "9091:9091"
    environment:
      <<: *kafka-env
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:9091
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper

  kafka1:
    image: confluentinc/cp-kafka:${CONFLUENT_VERSION}
    hostname: kafka1
    container_name: kafka1
    ports:
      - "9092:9092"
    environment:
      <<: *kafka-env
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_BROKER_ID: 2
    depends_on:
      - zookeeper

  kafka-rest:
    image: confluentinc/cp-kafka-rest:${CONFLUENT_VERSION}
    hostname: kafka-rest
    container_name: kafka-rest
    ports:
      - "8080:8080"
    environment:
      KAFKA_REST_HOST_NAME: kafka-rest
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka0:9091,PLAINTEXT://kafka1:9092
      KAFKA_REST_LISTENERS: http://0.0.0.0:8080
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://localhost:8085
    depends_on:
      - kafka0
      - kafka1
